### ISSUE TITLE
Improving "addTrackToUndoStack" function

### ISSUE THREAD

**Issue by IPHundead** [itsjibel/Ejib#21]
looking at "insert_mode.hpp", at lines like 279 and 300, the function "addTrackToUndoStack" has been used, but it has always been followed by/accompanied with "if (currentMode != "visual" && !UseForRedoing)" and "RedoStack.clear();". we could merge these with the function itself and make it so it takes "isWrite", "changeString", and "changeMode" (which are "addTrackToUndoStack's arguments" as arguments.

**Comment by itsjibel** [comment]
It makes sense, I commit it to the project
